### ISSUE TITLE
每章在奇数页起始？

### ISSUE THREAD

**Issue by zepinglee** [USTCThesis/USTCThesis-Rework#10]
我觉得有必要再讨论一下chapter从奇数页起始，aka openright；
教务处规定的是“每章另起一页”，aka openany，我觉得这一点没必要非要跟《规范》对着干吧。

我这里有本GTM73就是openany的，Knuth自己的Concrete Math也是openany的，所以openright也不是行业的硬性规范，毕竟springer和pearson也不能说是外行吧。

@ywgATustcbbs 在 https://github.com/ywgATustcbbs/ustcthesis/issues/12 说“制本厂装订的时候会提醒学生每章从奇数页开始”，我还想了解一下制本厂会干预多少排版问题？他们会自行插入空白页？

**Comment by seisman** [comment]
`openright`和`openany`之间可以直接通过`\documentclass`的选项来实现切换，可以供用户自己选择。

**Comment by seisman** [comment]
制本厂的干预其实没什么意义，毕竟论文是学生自己的，他们没有权利管排版的问题，顶多是提醒一下学生罢了。

打印正文、制作封面、胶装，这三个步骤，也就只有制作封面是必须在学校制本厂做的，其他的都可以自己DIY。

**Comment by zepinglee** [comment]
我知道可以自定义，我问的是默认情况设置的情况，用哪个更合适？

一个问题是，现在的abstract是用\chapter做的，如果改了openany，英文abstract就在中文摘要的背面了。

我想应该把默认的预设做好，省得他们一个个来问。

**Comment by seisman** [comment]
恩，我更倾向于openright，毕竟这样看上去更加直观，而且也是大多数书籍的处理方法。

至于openany的时候英文abstract的问题，应该可以加一个额外的cleardoublepage来解决吧？

**Comment by zepinglee** [comment]
我倾向于教务处规定的openany。所以召唤@ywgATustcbbs 来投票吧哈哈

**Comment by seisman** [comment]
我觉得选哪个都无所谓，只要在模板以及文档里都写清楚就好。

至于那些连写好的文档都不看遇到问题就问的人，还是不要浪费时间去回答了。。。
