### ISSUE TITLE
取消Makefile中的PDF预览？

### ISSUE THREAD

**Issue by seisman** [USTCThesis/USTCThesis-Rework#14]
`latexmk`的默认PDF预览工具是Adobe Reader。因而使用PDF预览功能会有若干问题：

1. Linux下默认是不安装Adobe Reader，因而会出现`sh: acroread: command not found`的错误。而Linux由于不会对文件进行锁定，所以完全可以用任意一款PDF阅读器打开PDF文件并一直保持打开的状态，每次编译完毕会自动刷新PDF。
2. 对于Windows用户而言，也不能保证所有人都有在使用Adobe Reader。如果使用了Adobe Reader，由于Windows会对文件进行锁定，所以每次编译前是需要手动关闭PDF文件的，那么编译完成之后手动打开一下也不麻烦。而对于使用sumatra的用户来说，则不需要手动关闭或打开PDF。

根据 http://superuser.com/questions/707483 的答案，是可以在`latexmk`配置文件中修改默认的PDF阅读器的，虽然改起来很简单，但是要给小白用户解释清楚还是有些困难的。

**Comment by zepinglee** [comment]
如果你不方便就删掉好了。

我写进这个是为了测试的时候方便，因为我用的atom编辑器，自己设置了一个快捷键自动保存执行make，但是无法带参数。当然，切换到终端再make; open main.pdf我也可以用。

还有那个Makefile也不算太完善，比如事实上main.pdf依赖于chapters/*.tex，但是还没写加进去，需要仔细研究一下GNU make的manual再写出最后的发布版。

**Comment by seisman** [comment]
这个Issue先留着吧，等最后结尾的时候再确定。
