### ISSUE TITLE
脚注的编号？

### ISSUE THREAD

**Issue by zepinglee** [USTCThesis/USTCThesis-Rework#15]
LaTeX脚注的默认样式就是这样的。需要换其他样式？

**Comment by seisman** [comment]
规范中并没有出现过对脚注的要求。

但是2.6.2.2节中说到：
   
    论文中的图、表、附注、公式、算式等,一律用阿拉伯数字分章依序连续编
    码。其标注形式应便于互相区别,如:图 l.1(第 1 章第一个图)、图 2.2(第二
    章第二个图);表 3.2(第三章第二个表)等。

我不确定这个附注是否是指脚注。

**Comment by zepinglee** [comment]
似乎附注是那种统一排在每一章后面的，不是在对应页的页脚。我回去查查footnote支持哪些格式
