### ISSUE TITLE
字体粗度问题

### ISSUE THREAD

**Issue by zepinglee** [USTCThesis/USTCThesis-Rework#17]
我研究了一下ctex在各个平台下对字体的定义，
1. 直接\bfseries 不一定能得到黑体，fandol宋体就有粗体的系列，\ bfseries得到的是fandol的粗宋体。
2. \heiti\bfseries 可以得到中文的黑体，但是在中英文混排的情况下，英文的字体就变成粗罗马体，结果衬线不一致会很难看；而且按照学校的论文风格，中文黑体的地方都对应于英文的sans字体。
所以我认为黑体一律用\sffamily表示，加粗的黑体用\sffamily\bfseries。
关于windows新系统，微软雅黑也是黑体啊；我没有用过不知道其排版效果，但是 https://github.com/CTeX-org/ctex-kit/issues/103 这里，刘海洋还是比较喜欢用微软雅黑的。

**Comment by seisman** [comment]
恩，没有问题，就按照`\sffamily`和`\sffamily\bfseries`即可。
