### ISSUE TITLE
脚注的链接无法点击

### ISSUE THREAD

**Issue by seisman** [USTCThesis/USTCThesis-Rework#21]
点击脚注时无反应，终端报错为`failed to look up xx`

**Comment by zepinglee** [comment]
你用的什么pdf阅读器？我用的skim没问题啊

**Comment by zepinglee** [comment]
你用的什么pdf阅读器？我用的skim没问题啊

**Comment by seisman** [comment]
Linux下用的是`evince`。

刚刚把PDF复制到Windows下用Adobe Acrobat打开，点击脚注的链接时无法跳转到脚注。

**Comment by zepinglee** [comment]
我发给你了一份我的build，你再试试……
我在 Mac 的 skim 和 preview 中都可以正常跳转

**Comment by seisman** [comment]
测试了你发给我的版本，可以正常跳转。

我这边原因未知，我在尝试把TeXLive 2015的宏包更新到最新版。

**Comment by seisman** [comment]
刚升级了43个包，现在编译生成的PDF里的脚注已经可以正常跳转了。

不知道是哪个包的bug，升级的包里可能相关的也就dvips和pdftex了。
