### ISSUE TITLE
将main.tex拆分成本科论文和硕博论文两个版本

### ISSUE THREAD

**Issue by seisman** [USTCThesis/USTCThesis-Rework#24]
目前`main.tex`中通过`\ifUSTC@opt@bachelor`判断是本科论文还是硕博论文，然后来安排frontmatter和backmatter中各个部分的顺序。

将本科论文和硕博论文放在一个文档里写，有如下几个缺点：
1. 部分命令仅对其中一个有效，比如`studentid`、`major`和`secret`
2. if条件语句中仅有一半对其中一个有效
3. 将内部的实现细节`\ifUSTC@opt@bachelor`暴露给用户

是否要将main.tex拆分成两个文档，分别针对本科论文和硕博论文，也方便后期适配本科论文时做测试。

**Comment by zepinglee** [comment]
搞分裂不好吧？
1. 无效的命令不管填不填，都不会产生问题，所以不用管这个。
2. 我觉得主要是一个顺序问题，可以写个说明让用户自己调整顺序吧。如果连这个都懒得做的人，态度太恶劣，还毕什么业啊。
3. 暴露这样一个命令确实不好

**Comment by seisman** [comment]
模板的作用不就是让别人偷懒么。。。如果是让用户自己调整命令的话，那`\ifUSTC@opt@bachelor`也不用写在文档里了。

**Comment by zepinglee** [comment]
我觉得不用手动设置参考文献列表的格式已经是最大的偷懒了……
对的，`\makeatletter`也可以去掉了，这样看上去也有种简洁的美。

**Comment by seisman** [comment]
`makeatletter`之类的如果能去掉最好去掉，忘了当初为什么要加了。

参考文献这东西，就算用Word也还是有人会用Endnote生成的，手动调整的人毕竟是少数。

**Comment by zepinglee** [comment]
@ 这个字符在.tex是特殊字符，在.cls里面是普通字符。这个命令是来切换的

**Comment by seisman** [comment]
恩，如果不影响最终效果的话，那就删掉吧

**Comment by zepinglee** [comment]
我增加了几个选项，print | pdf, openany | openright, pageright | pagecenter, 默认都是前者
