### ISSUE TITLE
使用空白还是波浪号？

### ISSUE THREAD

**Issue by seisman** [USTCThesis/USTCThesis-Rework#26]
ctex在处理中英文混排时会自动在中英文之间加上空格，但是在某些情况下不会。

测试代码：
~~~
\documentclass{ctexbook}
\begin{document}
中文测试\verb+abc+中文测试
\end{document}
~~~
图片上传不上来。。。你自己编译试一下。

实际编译的效果是`abc`后面有空格而前面无空格，效果非常丑。解决这个问题的写法有几种：
1. 前面加波浪号：`中文测试~\verb+abc+中文测试`
2. 前面加空格：`中文测试 \verb+abc+中文测试`
3. 为了对称，前后都加空格：`中文测试 \verb+abc+ 中文测试`

除了`\verb`外，还有`\ref`、`\nameref`、`\pageref`等等都有类似的问题。

你有什么看法？如果都可以的话至少统一一种风格。

**Comment by zepinglee** [comment]
我一开始想写得紧凑一些，就忘记了这个问题。
3 应该是标准写法，ctex.dtx 也是这么写的，并且代码里中、西文字符之间都有空格。我慢慢改吧……T-T
另外“~”是产生一个禁止在这里断行的空格。

**Comment by zepinglee** [comment]
另外有个关于 coding style 的问题，刘海洋在《LaTeX 入门》第476页写道，“TeX 代码的书写风格并没有一定要求，花括号不占一行、缩进两格的风格是最常见的……” 其实 ltx2e 的宏包基本是按照这个风格写的
我们有没有必要改为这个风格？

**Comment by seisman** [comment]
表示无法接受“花括号不占一行、缩进两格”这种风格。。。。

选什么风格无所谓，只要全文统一风格即可。

**Comment by zepinglee** [comment]
其实我也不太喜欢
