### ISSUE TITLE
字号的磅数是pt还是bp？

### ISSUE THREAD

**Issue by zepinglee** [USTCThesis/USTCThesis-Rework#4]
我只看到ctex用的bp，比如说小四是12bp不是12pt，这两个单位虽然差不多，但是毕竟还是不一样吧？

**Comment by seisman** [comment]
参考资料：
1. http://tex.stackexchange.com/questions/34024/setting-a-document-in-ms-word-12pt-12bp
2. https://en.wikipedia.org/wiki/Point_%28typography%29

>  The 12 point of Word will be PostScript point, which in TeX would be called 12bp. A TeX pt is slightly 
> smaller: it's 1/72.27 inch, while a bp/PostScript point is 1/72 inch. 

我还没来得及细看，按照上面的说法，TeX中：

1. pt: 欧美传统排版的长度单位 `1 inch = 72.27 pt`
2. bp: PostScript等电子排版领域中point都是bp，`1 inch = 72 bp`

而Word中的point是PostScript point，也就是TeX中的bp。

**Comment by zepinglee** [comment]
我去改一下吧

**Comment by seisman** [comment]
我还没有细看这几个参考资料，还不太确定。

**Comment by seisman** [comment]
基本已经确定。

Word中的1 point = 1/72 inch，即采用的是PostScript Point的定义。在LaTeX中应使用`bp`
