### ISSUE TITLE
“目录的书签”是什么意思？

### ISSUE THREAD

**Issue by zepinglee** [USTCThesis/USTCThesis-Rework#6]
Notes.rst 第三行，是指在PDF里面加书签吗？

**Comment by zepinglee** [comment]
另外我这两天尝试了用table去排版整个封面，但是没有找到固定每一行高度的方法。我用单独一列的`\rule`支撑起正确的高度，但是`\rule`的高度是从baseline算起的，需要一个修正值。

所以我决定先把titlepage放一边，等我看完 The TeXbook 和 LaTeX 源码的垂直距离部分再做这个。

**Comment by seisman** [comment]
那个Notes.rst是我当初在写的时候，记录下来的尚未实现的部分。

目录的书签指的是PDF里的书签，直接用`pdfbookmark`就可以添加。

**Comment by zepinglee** [comment]
另外这个 Note.rst 有其他用处吗？我打算把它整合进 README.md，少个文件看得舒心

**Comment by seisman** [comment]
Note.rst没有用，可以直接删除
